version: '3'
services:
  anyapp:
    container_name: anyapp
    build: 
      context: anyapp
      dockerfile: Dockerfile
    volumes:
      - common_logs:/common_logs
    environment:
      - LOG_FNAME="logs.txt"
    command: echo "I'm running > /common_logs/logs.txt"
  logservice: 
    container_name: logsevice
    build: 
      context: logservice
      dockerfile: Dockerfile
    volumes:
      - common_logs:/common_logs
    expose:
      - "3000"
    ports:
      - "80:3000"
    depends_on:
      - anyapp
    environment:
      - LOG_FNAME=logs.txt
volumes:
  common_logs:
  
 