version: '3'
services:
  js_app:
    container_name: js_app
    build: 
      context: js_app
      dockerfile: Dockerfile
    volumes:
      - common_logs:/common_logs
    expose:
      - "3001"
    ports:
      - "3001:3001"
    environment:
      - LOG_FNAME="logs.txt"
  logview: 
    container_name: logview
    build: 
      context: logview
      dockerfile: Dockerfile
    volumes:
      - common_logs:/common_logs
    expose:
      - "3000"
    ports:
      - "3000:3000"
    depends_on:
      - js_app
    environment:
      - LOG_FNAME=logs.txt
volumes:
  common_logs:
  
 